### ISSUE TITLE
Printf -v illegal operation

### ISSUE THREAD

**Issue by alphafox02** [M17-Project/M17_Implementations#13]
Seems that not all versions of printf have a -v option. Tried changing up the m17-sms.sh script to the following.

```
#!/bin/bash
 
if [ "$#" -lt 5 ]
then
        echo "Not enough parameters."
        echo "Usage: sh m17-sms.sh dst src can message output_file"
        echo "Exiting."
        exit
fi
 
str=$4
len=$(echo -n "$str" | wc -c)  # Calculate the length of the string
len=$((len + 2))  # Add 2 additional bytes (0x05 and 0x00)
 
# Create the message with the additional bytes
message="\x05$str\x00"
 
# Write the message to a temporary file
temp_file=$(mktemp)
echo -ne "$message" > "$temp_file"
 
# Encode the message and save it to the output file
m17-packet-encode -S "$2" -D "$1" -C "$3" -n "$len" -o "$5" < "$temp_file"
 
# Convert the output file to a WAV file using sox
sox -t raw -r 48000 -b 16 -c 1 -L -e signed-integer "$5" "$5.wav"
 
# Clean up the temporary file
rm "$temp_file"
```

**Comment by sp5wwp** [comment]
Have you tried encoding text ending with an exclamation mark?

**Comment by alphafox02** [comment]
I’ve not, I’m still working out how to send the encoded file(s) correctly with gnuradio. Assuming the above modification may not be the best idea?

**Comment by sp5wwp** [comment]
Use the .rrc file with the `File Source` block. See the `pkt_tx.grc` example flowgraph for details.

**Comment by sp5wwp** [comment]
I also updated the script.

**Comment by alphafox02** [comment]
Okay I think I tried that, but I’ll give it another go. So if I tx it that way and rx with the rx flowgraph and have the packet decoder looking at the fifo file - it should decode the text?

**Comment by sp5wwp** [comment]
Yes.

**Comment by sp5wwp** [comment]
Closing as fixed.

**Comment by alphafox02** [comment]
Last question, off main topic, but you said the file source.. there’s two blanked out file sources one with .aud and another with .bin. Use either of those or just simply add a new file source and hook direct to? Thank you.

**Comment by sp5wwp** [comment]
For the packet mode, you want to use the `pkt_tx.grc`.
