### ISSUE TITLE
m17-decoder-sym scrambler subtype is read incorrectly

### ISSUE THREAD

**Issue by lwvmobile** [M17-Project/M17_Implementations#34]
https://github.com/M17-Project/M17_Implementations/blob/cafde7fc61f9b155868bb6fb0bb2f0ee9cc009e3/SP5WWP/m17-decoder/m17-decoder-sym.c#L800

subytes should be 0, 1, and 2, and not 1,2,3 for 8, 16, and 24-bit scrambler subtypes.

**Comment by lwvmobile** [comment]
I found a couple minor issues on decryption I'm going to make a PR for soon. Noticed we aren't currently decrypting the last frame if it isn't a signed stream, and also, the 16-bit scrambler mode isn't quite working correctly, the seed is being truncated to 0xFF since its subtype isn't set yet, so just going to make some tweaks.

**Comment by sp5wwp** [comment]
> subytes should be 0, 1, and 2, and not 1,2,3 for 8, 16, and 24-bit scrambler subtypes.

Oops, I overlooked that :)

**Comment by sp5wwp** [comment]
Fixed.
